// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gophkeeper.proto

package gophkeeperv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretType int32

const (
	SecretType_UNSPECIFIED    SecretType = 0
	SecretType_LOGIN_PASSWORD SecretType = 1
	SecretType_TEXT           SecretType = 2
	SecretType_BINARY         SecretType = 3
	SecretType_CARD           SecretType = 4
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "LOGIN_PASSWORD",
		2: "TEXT",
		3: "BINARY",
		4: "CARD",
	}
	SecretType_value = map[string]int32{
		"UNSPECIFIED":    0,
		"LOGIN_PASSWORD": 1,
		"TEXT":           2,
		"BINARY":         3,
		"CARD":           4,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_gophkeeper_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretType.Descriptor instead.
func (SecretType) EnumDescriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{1}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{3}
}

type CreateSecretRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Title      string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	SecretType SecretType             `protobuf:"varint,2,opt,name=secret_type,json=secretType,proto3,enum=gophkeeper.v1.SecretType" json:"secret_type,omitempty"`
	// custom key-value data
	Metadata string `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// login_password
	Login    string `protobuf:"bytes,4,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	// text
	TextData string `protobuf:"bytes,6,opt,name=text_data,json=textData,proto3" json:"text_data,omitempty"`
	// binary
	BinaryData []byte `protobuf:"bytes,7,opt,name=binary_data,json=binaryData,proto3" json:"binary_data,omitempty"`
	// card
	CardNumber    string `protobuf:"bytes,8,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardExp       string `protobuf:"bytes,9,opt,name=card_exp,json=cardExp,proto3" json:"card_exp,omitempty"`
	CardHolder    string `protobuf:"bytes,10,opt,name=card_holder,json=cardHolder,proto3" json:"card_holder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSecretRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSecretRequest) GetSecretType() SecretType {
	if x != nil {
		return x.SecretType
	}
	return SecretType_UNSPECIFIED
}

func (x *CreateSecretRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *CreateSecretRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CreateSecretRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateSecretRequest) GetTextData() string {
	if x != nil {
		return x.TextData
	}
	return ""
}

func (x *CreateSecretRequest) GetBinaryData() []byte {
	if x != nil {
		return x.BinaryData
	}
	return nil
}

func (x *CreateSecretRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CreateSecretRequest) GetCardExp() string {
	if x != nil {
		return x.CardExp
	}
	return ""
}

func (x *CreateSecretRequest) GetCardHolder() string {
	if x != nil {
		return x.CardHolder
	}
	return ""
}

type CreateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{5}
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *GetSecretRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetSecretResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId     int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title      string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt  string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata   string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	SecretType SecretType             `protobuf:"varint,7,opt,name=secret_type,json=secretType,proto3,enum=gophkeeper.v1.SecretType" json:"secret_type,omitempty"`
	// login_password
	Login    string `protobuf:"bytes,8,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`
	// text
	TextData string `protobuf:"bytes,10,opt,name=text_data,json=textData,proto3" json:"text_data,omitempty"`
	// binary
	BinaryData []byte `protobuf:"bytes,11,opt,name=binary_data,json=binaryData,proto3" json:"binary_data,omitempty"`
	// card
	CardNumber    string `protobuf:"bytes,12,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardExp       string `protobuf:"bytes,13,opt,name=card_exp,json=cardExp,proto3" json:"card_exp,omitempty"`
	CardHolder    string `protobuf:"bytes,14,opt,name=card_holder,json=cardHolder,proto3" json:"card_holder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *GetSecretResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetSecretResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetSecretResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetSecretResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetSecretResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetSecretResponse) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *GetSecretResponse) GetSecretType() SecretType {
	if x != nil {
		return x.SecretType
	}
	return SecretType_UNSPECIFIED
}

func (x *GetSecretResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetSecretResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetSecretResponse) GetTextData() string {
	if x != nil {
		return x.TextData
	}
	return ""
}

func (x *GetSecretResponse) GetBinaryData() []byte {
	if x != nil {
		return x.BinaryData
	}
	return nil
}

func (x *GetSecretResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *GetSecretResponse) GetCardExp() string {
	if x != nil {
		return x.CardExp
	}
	return ""
}

func (x *GetSecretResponse) GetCardHolder() string {
	if x != nil {
		return x.CardHolder
	}
	return ""
}

type GetSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsRequest) Reset() {
	*x = GetSecretsRequest{}
	mi := &file_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsRequest) ProtoMessage() {}

func (x *GetSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsRequest.ProtoReflect.Descriptor instead.
func (*GetSecretsRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{8}
}

type GetSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*Secret              `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsResponse) Reset() {
	*x = GetSecretsResponse{}
	mi := &file_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsResponse) ProtoMessage() {}

func (x *GetSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsResponse.ProtoReflect.Descriptor instead.
func (*GetSecretsResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{9}
}

func (x *GetSecretsResponse) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSecretRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{11}
}

// Common
type Secret struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId     int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title      string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt  string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata   string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	SecretType SecretType             `protobuf:"varint,7,opt,name=secret_type,json=secretType,proto3,enum=gophkeeper.v1.SecretType" json:"secret_type,omitempty"`
	// login_password
	Login    string `protobuf:"bytes,8,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`
	// text
	TextData string `protobuf:"bytes,10,opt,name=text_data,json=textData,proto3" json:"text_data,omitempty"`
	// binary
	BinaryData []byte `protobuf:"bytes,11,opt,name=binary_data,json=binaryData,proto3" json:"binary_data,omitempty"`
	// card
	CardNumber    string `protobuf:"bytes,12,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardExp       string `protobuf:"bytes,13,opt,name=card_exp,json=cardExp,proto3" json:"card_exp,omitempty"`
	CardHolder    string `protobuf:"bytes,14,opt,name=card_holder,json=cardHolder,proto3" json:"card_holder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{12}
}

func (x *Secret) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Secret) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Secret) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Secret) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Secret) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Secret) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Secret) GetSecretType() SecretType {
	if x != nil {
		return x.SecretType
	}
	return SecretType_UNSPECIFIED
}

func (x *Secret) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Secret) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Secret) GetTextData() string {
	if x != nil {
		return x.TextData
	}
	return ""
}

func (x *Secret) GetBinaryData() []byte {
	if x != nil {
		return x.BinaryData
	}
	return nil
}

func (x *Secret) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *Secret) GetCardExp() string {
	if x != nil {
		return x.CardExp
	}
	return ""
}

func (x *Secret) GetCardHolder() string {
	if x != nil {
		return x.CardHolder
	}
	return ""
}

var File_gophkeeper_proto protoreflect.FileDescriptor

const file_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x10gophkeeper.proto\x12\rgophkeeper.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"a\n" +
	"\x0fRegisterRequest\x12\"\n" +
	"\x05login\x18\x01 \x01(\tB\f\x92A\tJ\a\"login\"R\x05login\x12*\n" +
	"\bpassword\x18\x02 \x01(\tB\x0e\x92A\vJ\t\"12pass!\"R\bpassword\"\x12\n" +
	"\x10RegisterResponse\"^\n" +
	"\fLoginRequest\x12\"\n" +
	"\x05login\x18\x01 \x01(\tB\f\x92A\tJ\a\"login\"R\x05login\x12*\n" +
	"\bpassword\x18\x02 \x01(\tB\x0e\x92A\vJ\t\"12pass!\"R\bpassword\"\x0f\n" +
	"\rLoginResponse\"\x98\x04\n" +
	"\x13CreateSecretRequest\x12\"\n" +
	"\x05title\x18\x01 \x01(\tB\f\x92A\tJ\a\"title\"R\x05title\x12b\n" +
	"\vsecret_type\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeB&\x92A#J!\"login_password|text|binary|card\"R\n" +
	"secretType\x12/\n" +
	"\bmetadata\x18\x03 \x01(\tB\x13\x92A\x10J\x0e\"site addr.ru\"R\bmetadata\x12\"\n" +
	"\x05login\x18\x04 \x01(\tB\f\x92A\tJ\a\"login\"R\x05login\x12+\n" +
	"\bpassword\x18\x05 \x01(\tB\x0f\x92A\fJ\n" +
	"\"password\"R\bpassword\x12-\n" +
	"\ttext_data\x18\x06 \x01(\tB\x10\x92A\rJ\v\"text data\"R\btextData\x120\n" +
	"\vbinary_data\x18\a \x01(\fB\x0f\x92A\fJ\n" +
	"\"AQIDBAUG\"R\n" +
	"binaryData\x128\n" +
	"\vcard_number\x18\b \x01(\tB\x17\x92A\x14J\x12\"4111111111111111\"R\n" +
	"cardNumber\x12'\n" +
	"\bcard_exp\x18\t \x01(\tB\f\x92A\tJ\a\"12/27\"R\acardExp\x123\n" +
	"\vcard_holder\x18\n" +
	" \x01(\tB\x12\x92A\x0fJ\r\"IVAN IVANOV\"R\n" +
	"cardHolder\"\x16\n" +
	"\x14CreateSecretResponse\"6\n" +
	"\x10GetSecretRequest\x12\"\n" +
	"\x05title\x18\x01 \x01(\tB\f\x92A\tJ\a\"title\"R\x05title\"\xd5\x05\n" +
	"\x11GetSecretResponse\x12\x18\n" +
	"\x02id\x18\x01 \x01(\x03B\b\x92A\x05J\x03\"1\"R\x02id\x12!\n" +
	"\auser_id\x18\x02 \x01(\x03B\b\x92A\x05J\x03\"1\"R\x06userId\x12\"\n" +
	"\x05title\x18\x03 \x01(\tB\f\x92A\tJ\a\"title\"R\x05title\x12?\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tB \x92A\x1dJ\x1b\"2026-04-16T15:44:00+03:00\"R\tcreatedAt\x12?\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tB \x92A\x1dJ\x1b\"2026-04-16T15:44:00+03:00\"R\tupdatedAt\x12/\n" +
	"\bmetadata\x18\x06 \x01(\tB\x13\x92A\x10J\x0e\"site addr.ru\"R\bmetadata\x12b\n" +
	"\vsecret_type\x18\a \x01(\x0e2\x19.gophkeeper.v1.SecretTypeB&\x92A#J!\"login_password|text|binary|card\"R\n" +
	"secretType\x12\"\n" +
	"\x05login\x18\b \x01(\tB\f\x92A\tJ\a\"login\"R\x05login\x12+\n" +
	"\bpassword\x18\t \x01(\tB\x0f\x92A\fJ\n" +
	"\"password\"R\bpassword\x12-\n" +
	"\ttext_data\x18\n" +
	" \x01(\tB\x10\x92A\rJ\v\"text data\"R\btextData\x120\n" +
	"\vbinary_data\x18\v \x01(\fB\x0f\x92A\fJ\n" +
	"\"AQIDBAUG\"R\n" +
	"binaryData\x128\n" +
	"\vcard_number\x18\f \x01(\tB\x17\x92A\x14J\x12\"4111111111111111\"R\n" +
	"cardNumber\x12'\n" +
	"\bcard_exp\x18\r \x01(\tB\f\x92A\tJ\a\"12/27\"R\acardExp\x123\n" +
	"\vcard_holder\x18\x0e \x01(\tB\x12\x92A\x0fJ\r\"IVAN IVANOV\"R\n" +
	"cardHolder\"\x13\n" +
	"\x11GetSecretsRequest\"E\n" +
	"\x12GetSecretsResponse\x12/\n" +
	"\asecrets\x18\x01 \x03(\v2\x15.gophkeeper.v1.SecretR\asecrets\"9\n" +
	"\x13DeleteSecretRequest\x12\"\n" +
	"\x05title\x18\x01 \x01(\tB\f\x92A\tJ\a\"title\"R\x05title\"\x16\n" +
	"\x14DeleteSecretResponse\"\xca\x05\n" +
	"\x06Secret\x12\x18\n" +
	"\x02id\x18\x01 \x01(\x03B\b\x92A\x05J\x03\"1\"R\x02id\x12!\n" +
	"\auser_id\x18\x02 \x01(\x03B\b\x92A\x05J\x03\"1\"R\x06userId\x12\"\n" +
	"\x05title\x18\x03 \x01(\tB\f\x92A\tJ\a\"title\"R\x05title\x12?\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tB \x92A\x1dJ\x1b\"2026-04-16T15:44:00+03:00\"R\tcreatedAt\x12?\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tB \x92A\x1dJ\x1b\"2026-04-16T15:44:00+03:00\"R\tupdatedAt\x12/\n" +
	"\bmetadata\x18\x06 \x01(\tB\x13\x92A\x10J\x0e\"site addr.ru\"R\bmetadata\x12b\n" +
	"\vsecret_type\x18\a \x01(\x0e2\x19.gophkeeper.v1.SecretTypeB&\x92A#J!\"login_password|text|binary|card\"R\n" +
	"secretType\x12\"\n" +
	"\x05login\x18\b \x01(\tB\f\x92A\tJ\a\"login\"R\x05login\x12+\n" +
	"\bpassword\x18\t \x01(\tB\x0f\x92A\fJ\n" +
	"\"password\"R\bpassword\x12-\n" +
	"\ttext_data\x18\n" +
	" \x01(\tB\x10\x92A\rJ\v\"text data\"R\btextData\x120\n" +
	"\vbinary_data\x18\v \x01(\fB\x0f\x92A\fJ\n" +
	"\"AQIDBAUG\"R\n" +
	"binaryData\x128\n" +
	"\vcard_number\x18\f \x01(\tB\x17\x92A\x14J\x12\"4111111111111111\"R\n" +
	"cardNumber\x12'\n" +
	"\bcard_exp\x18\r \x01(\tB\f\x92A\tJ\a\"12/27\"R\acardExp\x123\n" +
	"\vcard_holder\x18\x0e \x01(\tB\x12\x92A\x0fJ\r\"IVAN IVANOV\"R\n" +
	"cardHolder*Q\n" +
	"\n" +
	"SecretType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eLOGIN_PASSWORD\x10\x01\x12\b\n" +
	"\x04TEXT\x10\x02\x12\n" +
	"\n" +
	"\x06BINARY\x10\x03\x12\b\n" +
	"\x04CARD\x10\x042\xb4\b\n" +
	"\n" +
	"Gophkeeper\x12h\n" +
	"\bRegister\x12\x1e.gophkeeper.v1.RegisterRequest\x1a\x1f.gophkeeper.v1.RegisterResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/register\x12\\\n" +
	"\x05Login\x12\x1b.gophkeeper.v1.LoginRequest\x1a\x1c.gophkeeper.v1.LoginResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/login\x12\xdd\x01\n" +
	"\fCreateSecret\x12\".gophkeeper.v1.CreateSecretRequest\x1a#.gophkeeper.v1.CreateSecretResponse\"\x83\x01\x92A`\x1a^Creates a secret for the user. Requires `Authorization` in gRPC metadata / for HTTP in headers\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/create-secret\x12\xcc\x01\n" +
	"\tGetSecret\x12\x1f.gophkeeper.v1.GetSecretRequest\x1a .gophkeeper.v1.GetSecretResponse\"|\x92A\\\x1aZGet a secret for the user. Requires `Authorization` in gRPC metadata / for HTTP in headers\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/get-secret\x12\xd1\x01\n" +
	"\n" +
	"GetSecrets\x12 .gophkeeper.v1.GetSecretsRequest\x1a!.gophkeeper.v1.GetSecretsResponse\"~\x92A]\x1a[Get a secrets for the user. Requires `Authorization` in gRPC metadata / for HTTP in headers\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/get-secrets\x12\xda\x01\n" +
	"\fDeleteSecret\x12\".gophkeeper.v1.DeleteSecretRequest\x1a#.gophkeeper.v1.DeleteSecretResponse\"\x80\x01\x92A]\x1a[Get a secrets for the user. Requires `Authorization` in gRPC metadata / for HTTP in headers\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/delete-secretBAZ?github.com/ibeloyar/gophkeeper/proto/gophkeeper/v1;gophkeeperv1b\x06proto3"

var (
	file_gophkeeper_proto_rawDescOnce sync.Once
	file_gophkeeper_proto_rawDescData []byte
)

func file_gophkeeper_proto_rawDescGZIP() []byte {
	file_gophkeeper_proto_rawDescOnce.Do(func() {
		file_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_proto_rawDesc), len(file_gophkeeper_proto_rawDesc)))
	})
	return file_gophkeeper_proto_rawDescData
}

var file_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_gophkeeper_proto_goTypes = []any{
	(SecretType)(0),              // 0: gophkeeper.v1.SecretType
	(*RegisterRequest)(nil),      // 1: gophkeeper.v1.RegisterRequest
	(*RegisterResponse)(nil),     // 2: gophkeeper.v1.RegisterResponse
	(*LoginRequest)(nil),         // 3: gophkeeper.v1.LoginRequest
	(*LoginResponse)(nil),        // 4: gophkeeper.v1.LoginResponse
	(*CreateSecretRequest)(nil),  // 5: gophkeeper.v1.CreateSecretRequest
	(*CreateSecretResponse)(nil), // 6: gophkeeper.v1.CreateSecretResponse
	(*GetSecretRequest)(nil),     // 7: gophkeeper.v1.GetSecretRequest
	(*GetSecretResponse)(nil),    // 8: gophkeeper.v1.GetSecretResponse
	(*GetSecretsRequest)(nil),    // 9: gophkeeper.v1.GetSecretsRequest
	(*GetSecretsResponse)(nil),   // 10: gophkeeper.v1.GetSecretsResponse
	(*DeleteSecretRequest)(nil),  // 11: gophkeeper.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil), // 12: gophkeeper.v1.DeleteSecretResponse
	(*Secret)(nil),               // 13: gophkeeper.v1.Secret
}
var file_gophkeeper_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.v1.CreateSecretRequest.secret_type:type_name -> gophkeeper.v1.SecretType
	0,  // 1: gophkeeper.v1.GetSecretResponse.secret_type:type_name -> gophkeeper.v1.SecretType
	13, // 2: gophkeeper.v1.GetSecretsResponse.secrets:type_name -> gophkeeper.v1.Secret
	0,  // 3: gophkeeper.v1.Secret.secret_type:type_name -> gophkeeper.v1.SecretType
	1,  // 4: gophkeeper.v1.Gophkeeper.Register:input_type -> gophkeeper.v1.RegisterRequest
	3,  // 5: gophkeeper.v1.Gophkeeper.Login:input_type -> gophkeeper.v1.LoginRequest
	5,  // 6: gophkeeper.v1.Gophkeeper.CreateSecret:input_type -> gophkeeper.v1.CreateSecretRequest
	7,  // 7: gophkeeper.v1.Gophkeeper.GetSecret:input_type -> gophkeeper.v1.GetSecretRequest
	9,  // 8: gophkeeper.v1.Gophkeeper.GetSecrets:input_type -> gophkeeper.v1.GetSecretsRequest
	11, // 9: gophkeeper.v1.Gophkeeper.DeleteSecret:input_type -> gophkeeper.v1.DeleteSecretRequest
	2,  // 10: gophkeeper.v1.Gophkeeper.Register:output_type -> gophkeeper.v1.RegisterResponse
	4,  // 11: gophkeeper.v1.Gophkeeper.Login:output_type -> gophkeeper.v1.LoginResponse
	6,  // 12: gophkeeper.v1.Gophkeeper.CreateSecret:output_type -> gophkeeper.v1.CreateSecretResponse
	8,  // 13: gophkeeper.v1.Gophkeeper.GetSecret:output_type -> gophkeeper.v1.GetSecretResponse
	10, // 14: gophkeeper.v1.Gophkeeper.GetSecrets:output_type -> gophkeeper.v1.GetSecretsResponse
	12, // 15: gophkeeper.v1.Gophkeeper.DeleteSecret:output_type -> gophkeeper.v1.DeleteSecretResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_gophkeeper_proto_init() }
func file_gophkeeper_proto_init() {
	if File_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_proto_rawDesc), len(file_gophkeeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_proto_goTypes,
		DependencyIndexes: file_gophkeeper_proto_depIdxs,
		EnumInfos:         file_gophkeeper_proto_enumTypes,
		MessageInfos:      file_gophkeeper_proto_msgTypes,
	}.Build()
	File_gophkeeper_proto = out.File
	file_gophkeeper_proto_goTypes = nil
	file_gophkeeper_proto_depIdxs = nil
}
